"""
Stage 2-B — uvicorn entry point for the finance API server.

Usage
─────
  python3 -m finance.server              # production (host/port from settings.toml)
  python3 -m finance.server --reload     # dev mode with auto-reload on file changes
  python3 -m finance.server --port 8091  # override port
  python3 -m finance.server --host 127.0.0.1

The host and port default to the [fastapi] section in config/settings.toml:
  host = "0.0.0.0"
  port = 8090

API docs (auto-generated by FastAPI):
  http://localhost:8090/docs        ← Swagger UI
  http://localhost:8090/redoc       ← ReDoc
"""
from __future__ import annotations
import argparse
import logging
import sys
from pathlib import Path

import uvicorn

from finance.config import load_config, get_fastapi_config, get_coretax_config

log = logging.getLogger(__name__)


def main():
    parser = argparse.ArgumentParser(
        description="Start the Stage 2 FastAPI finance server.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python3 -m finance.server                    # start on :8090
  python3 -m finance.server --reload           # dev mode
  python3 -m finance.server --port 8091        # custom port
  python3 -m finance.server --host 127.0.0.1  # localhost only
        """,
    )
    parser.add_argument("--host",   help="Bind host (overrides settings.toml)")
    parser.add_argument("--port",   type=int, help="Bind port (overrides settings.toml)")
    parser.add_argument("--reload", action="store_true", help="Auto-reload on file changes (dev)")
    parser.add_argument(
        "--config", metavar="PATH",
        help="Path to settings.toml (default: config/settings.toml)",
    )
    args = parser.parse_args()

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s  %(levelname)-7s  %(message)s",
        datefmt="%H:%M:%S",
        stream=sys.stdout,
    )

    cfg     = load_config(args.config)
    api_cfg = get_fastapi_config(cfg)
    coretax_cfg = get_coretax_config(cfg)

    Path(coretax_cfg.template_dir).mkdir(parents=True, exist_ok=True)
    Path(coretax_cfg.output_dir).mkdir(parents=True, exist_ok=True)

    host = args.host or api_cfg.host
    port = args.port or api_cfg.port

    log.info("Starting Finance API on %s:%d …", host, port)
    log.info("Swagger UI → http://localhost:%d/docs", port)

    uvicorn.run(
        "finance.api:app",
        host=host,
        port=port,
        reload=args.reload,
        log_level="info",
    )


if __name__ == "__main__":
    main()
