// Indonesian labels — all user-facing text in one place
export default {
  appName: 'Pengeluaran Rumah',
  addExpense: 'Tambah Pengeluaran',
  history: 'Riwayat',
  logout: 'Keluar',
  login: 'Masuk',
  username: 'Username',
  password: 'Password',
  amount: 'Jumlah (Rp)',
  category: 'Kategori',
  merchant: 'Toko / Penjual',
  description: 'Deskripsi',
  paymentMethod: 'Metode Pembayaran',
  cash: 'Tunai',
  transfer: 'Transfer',
  ewallet: 'Lainnya',
  date: 'Tanggal',
  time: 'Jam',
  note: 'Catatan',
  notePlaceholder: 'Opsional',
  save: 'Simpan',
  cancel: 'Batal',
  delete: 'Hapus',
  edit: 'Edit',
  deleteConfirm: 'Hapus transaksi ini?',
  savedOk: 'Tersimpan ✓',
  saveFailed: 'Gagal menyimpan',
  deletedOk: 'Dihapus ✓',
  noTransactions: 'Belum ada transaksi',
  welcome: 'Selamat datang, {name}',
  loginFailed: 'Username atau password salah',
  sessionExpired: 'Sesi habis, silakan masuk kembali',
  loadMore: 'Muat lebih banyak',
}
